repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    # -   repo: https://github.com/psf/black
    #     rev: 22.10.0
    #     hooks:
    #     -   id: black
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
      rev: "v0.0.261"
      hooks:
          - id: ruff
    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports
    - repo: https://github.com/omnilib/ufmt
      rev: v2.0.0
      hooks:
          - id: ufmt
            additional_dependencies:
                - black == 22.6.0
                - usort == 1.0.4
